CREATE DATABASE T_SSolve;
USE T_SSolve;

CREATE TABLE Clientes(
	IdCliente INT PRIMARY KEY IDENTITY,
	NomeFantasia VARCHAR(250) NOT NULL UNIQUE,
	RazaoSocial VARCHAR(400) NOT NULL UNIQUE,
	CNPJ VARCHAR(200) NOT NULL UNIQUE,
	Endereco VARCHAR(400) NOT NULL UNIQUE 
);

CREATE TABLE Comodos (
	IdComodo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(250) NOT NULL
);

CREATE TABLE Servicos (
	IdServico INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(250) NOT NULL,
	Preco VARCHAR(250) NOT NULL,
	DataInicio DATETIME NOT NULL,
	DataTermino DATETIME,
	IdCliente INT FOREIGN KEY REFERENCES Clientes (IdCliente),
	IdComodo INT FOREIGN KEY REFERENCES Comodos (IdComodo)
);

CREATE TABLE Funcionarios (
	IdFuncionario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(250) NOT NULL,
	Salario VARCHAR(250) NOT NULL
);

CREATE TABLE ServicosFuncionarios (
	IdServico INT FOREIGN KEY REFERENCES Servicos (IdServico),
	IdFuncionario INT FOREIGN KEY REFERENCES Funcionarios (IdFuncionario),
);

