CREATE DATABASE T_HRoads;
USE T_HRoads;

CREATE TABLE Classes (
	IdClasse INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE Habilidades (
	IdHabilidade INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200) NOT NULL UNIQUE,
	IdTipo INT FOREIGN KEY REFERENCES TipoHabilidades(IdTipo)
)

CREATE TABLE TipoHabilidades (
	IdTipo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE ClasseHabilidade (
	IdClasse INT FOREIGN KEY REFERENCES Classes(IdClasse),
	IdHabilidade INT FOREIGN KEY REFERENCES Habilidades(IdHabilidade)
);

CREATE TABLE Personagem (
	IdPersonagem INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200) NOT NULL UNIQUE,
	CapacidadeMaxVida INT NOT NULL,
	CapacidadeMaxMana INT NOT NULL,
	DataAtualizacao DATE,
	DataCriacao DATE,
	IdClasse INT FOREIGN KEY REFERENCES Classes(IdClasse)
)


