CREATE DATABASE T_Opflix;
USE T_Opflix;

CREATE TABLE Perfil(
	IdPerfil INT PRIMARY KEY IDENTITY NOT NULL,
	TipoPerfil VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Usuarios(
	IdUsuario INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(250) NOT NULL,
	Email VARCHAR(250) UNIQUE NOT NULL, 
	Senha VARCHAR(250) NOT NULL,
	IdPerfil INT FOREIGN KEY REFERENCES Perfil(IdPerfil)
);

CREATE TABLE Categorias(
	IdCategoria INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE TipoConteudo(
	IdTipoConteudo INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE Plataformas (
	IdPlataforma INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE Lancamentos(
	IdLancamento INT PRIMARY KEY IDENTITY NOT NULL,
	DataLancamento DATE NOT NULL,
	Duracao TIME NOT NULL,
	Titulo VARCHAR(250) NOT NULL,
	Sinopse VARCHAR(2000) NOT NULL,
	IdCategoria INT FOREIGN KEY REFERENCES Categorias(IdCategoria),
	IdTipoConteudo INT FOREIGN KEY REFERENCES TipoConteudo(IdTipoConteudo)
);

CREATE TABLE PlataformaLancamento (
	IdLancamento INT FOREIGN KEY REFERENCES Lancamentos(IdLancamento),
	IdPlataforma INT FOREIGN KEY REFERENCES Plataformas(IdPlataforma)
);

---------------- EXTRAS --------------------

ALTER TABLE Usuarios ADD FotoPerfil VARCHAR(500);


